version: '3'

services:
  app:
    container_name: credit-application
    build: .
    tty: true
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app

    # porta utilizada <servidor>:<container>
    ports:
      - 8080:8080